param([Parameter(Mandatory)][string]$OutFile,[string]$TempTool,[switch]$ApplySafe)
$ErrorActionPreference='SilentlyContinue'; $temp=@($env:TEMP,"$env:windir\Temp"); $bytes=0
foreach($d in $temp){if(Test-Path $d){Get-ChildItem $d -File -Recurse -Force|Where-Object LastWriteTime -lt (Get-Date).AddDays(-7)|ForEach-Object{$bytes+=$_.Length}}}
$gb=[math]::Round($bytes/1GB,2); $startup=(Get-CimInstance Win32_StartupCommand).Count; $reboot=(Test-Path 'HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Component Based Servicing\RebootPending') -or (Test-Path 'HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\WindowsUpdate\Auto Update\RebootRequired')
$trim=(fsutil behavior query DisableDeleteNotify 2>$null|Out-String); $sysErrors=(Get-WinEvent -FilterHashtable @{LogName='System';StartTime=(Get-Date).AddDays(-7);Level=1,2} -MaxEvents 100|Where-Object ProviderName -match 'WHEA|Disk|Ntfs|stornvme').Count
$r=@('WINTOOL - SMART MAINTENANCE',('Date: '+(Get-Date)),'',('Old temporary files: '+$gb+' GB'),('Startup entries: '+$startup),('TRIM: '+$(if($trim -match 'DisableDeleteNotify = 0'){'ACTIVE'}else{'CHECK'})),('Recent hardware/disk errors: '+$sysErrors),('Pending restart: '+$(if($reboot){'YES'}else{'NO'})),'','RECOMMENDATIONS')
if($gb -ge .5){$r+='[RECOMMENDED] Clean temporary files older than 7 days.'}else{$r+='[OK] Temporary files are under control.'}; if($startup -gt 12){$r+='[CHECK] Review startup applications.'}else{$r+='[OK] Startup is reasonable.'}; if($sysErrors -gt 0){$r+='[CHECK] Hardware/disk events were found; review the report/events.'}else{$r+='[OK] No WHEA/Disk/NTFS alerts were found in the sample.'}; if($reboot){$r+='[INFO] Windows has a pending restart.'}
if($ApplySafe){$r+='';$r+='ACTIONS'; if($gb -ge .5 -and (Test-Path $TempTool)){& $TempTool; $r+='[APPLIED] Old temporary files cleaned.'}else{$r+='[NO CHANGES] No cleanup was recommended.'}; try{Optimize-Volume -DriveLetter C -Analyze -ErrorAction Stop|Out-Null;$r+='[OK] C: optimization analysis completed (read-only).'}catch{$r+='[INFO] Optimize-Volume analysis could not be completed.'}}
$r|Set-Content -LiteralPath $OutFile -Encoding UTF8
