param([Parameter(Mandatory)][string]$OutFile,[string]$TempTool,[switch]$ApplySafe)
$ErrorActionPreference='SilentlyContinue'; $temp=@($env:TEMP,"$env:windir\Temp"); $bytes=0
foreach($d in $temp){if(Test-Path $d){Get-ChildItem $d -File -Recurse -Force|Where-Object LastWriteTime -lt (Get-Date).AddDays(-7)|ForEach-Object{$bytes+=$_.Length}}}
$gb=[math]::Round($bytes/1GB,2); $startup=(Get-CimInstance Win32_StartupCommand).Count; $reboot=(Test-Path 'HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Component Based Servicing\RebootPending') -or (Test-Path 'HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\WindowsUpdate\Auto Update\RebootRequired')
$trim=(fsutil behavior query DisableDeleteNotify 2>$null|Out-String); $sysErrors=(Get-WinEvent -FilterHashtable @{LogName='System';StartTime=(Get-Date).AddDays(-7);Level=1,2} -MaxEvents 100|Where-Object ProviderName -match 'WHEA|Disk|Ntfs|stornvme').Count
$r=@('WINTOOL V5 - MANTENIMIENTO INTELIGENTE',('Fecha: '+(Get-Date)),'',('Temporales antiguos: '+$gb+' GB'),('Entradas de inicio: '+$startup),('TRIM: '+$(if($trim -match 'DisableDeleteNotify = 0'){'ACTIVO'}else{'REVISAR'})),('Errores hardware/disco recientes: '+$sysErrors),('Reinicio pendiente: '+$(if($reboot){'SI'}else{'NO'})),'','RECOMENDACIONES')
if($gb -ge .5){$r+='[RECOMENDADO] Limpiar temporales de mas de 7 dias.'}else{$r+='[OK] Temporales bajo control.'}; if($startup -gt 12){$r+='[REVISAR] Revisar aplicaciones de inicio.'}else{$r+='[OK] Inicio razonable.'}; if($sysErrors -gt 0){$r+='[REVISAR] Hay eventos de hardware/disco; revisar reporte/eventos.'}else{$r+='[OK] Sin alertas WHEA/Disk/NTFS en la muestra.'}; if($reboot){$r+='[INFO] Windows tiene un reinicio pendiente.'}
if($ApplySafe){$r+='';$r+='ACCIONES'; if($gb -ge .5 -and (Test-Path $TempTool)){& $TempTool; $r+='[APLICADO] Limpieza de temporales antiguos.'}else{$r+='[SIN CAMBIOS] No habia limpieza recomendada.'}; try{Optimize-Volume -DriveLetter C -Analyze -ErrorAction Stop|Out-Null;$r+='[OK] Analisis de optimizacion de C: completado (solo lectura).'}catch{$r+='[INFO] No se pudo analizar Optimize-Volume.'}}
$r|Set-Content -LiteralPath $OutFile -Encoding UTF8
